#!/bin/sh
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [URI OR LOCAL FILE]"
    exit
fi

gst-play-1.0 "$1"
gst-launch-1.0 urisourcebin uri="$1" ! decodebin ! audioconvert ! audioresample ! autoaudiosink
